# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGCYK8OoPBe2NNR4Oq-lulCwAYmIj2rJ
"""

import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
titanic_data = sns.load_dataset('titanic')
titanic_data.head()

sns.countplot(x='survived', data=titanic_data)
plt.title('Survival Rate')
plt.show()

sex_counts = titanic_data['sex'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(sex_counts, labels=sex_counts.index, autopct='%1.1f%%', startangle=90)
plt.title('Passenger Distribution by Sex')
plt.axis('equal')
plt.show()

sns.histplot(x='age', data=titanic_data, kde=True)
plt.title('Age Distribution')
plt.show()

titanic_data['pclass'].value_counts().sort_index().plot(kind='bar')
plt.title('Passenger Count by Class')
plt.xlabel('Passenger Class')
plt.ylabel('Number of Passengers')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='sex', hue='survived', data=titanic_data)
plt.title('Survival by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Passengers')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='pclass', hue='survived', data=titanic_data)
plt.title('Survival by Passenger Class')
plt.xlabel('Passenger Class')
plt.ylabel('Number of Passengers')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='pclass', hue='sex', data=titanic_data[titanic_data['survived'] == 1])
plt.title('Survivors by Gender and Passenger Class')
plt.xlabel('Passenger Class')
plt.ylabel('Number of Survivors')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='embarked', data=titanic_data, palette='Set2')
plt.title('Passenger Count by Embarkation Point')
plt.xlabel('Embarkation Port')
plt.ylabel('Number of Passengers')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='embarked', hue='survived', data=titanic_data, palette='Set1')
plt.title('Survival by Embarkation Point')
plt.xlabel('Embarkation Port')
plt.ylabel('Number of Passengers')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

titanic_data['fare_bin'] = pd.cut(titanic_data['fare'], bins=[0, 20, 50, 100, 600], labels=['Low', 'Medium', 'High', 'Very High'])

plt.figure(figsize=(6,4))
sns.countplot(x='fare_bin', hue='survived', data=titanic_data, palette='coolwarm')
plt.title('Survival by Fare Range')
plt.xlabel('Fare Range')
plt.ylabel('Number of Passengers')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

titanic_data['family_size'] = titanic_data['sibsp'] + titanic_data['parch']

plt.figure(figsize=(8,4))
sns.countplot(x='family_size', hue='survived', data=titanic_data, palette='Set3')
plt.title('Survival by Family Size')
plt.xlabel('Family Size')
plt.ylabel('Number of Passengers')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

g = sns.catplot(
    data=titanic_data,
    x='family_size', hue='sex', col='pclass',
    kind='count', height=4, aspect=1,
    palette='pastel'
)
g.fig.suptitle('Family Size by Gender and Passenger Class', y=1.05)
g.set_axis_labels('Family Size', 'Number of Passengers')
g.add_legend()
plt.show()

